services:
  payment-service-1:
    image: tiagodolphine/rinha-2025-payment-service:0.0.2
    environment:
      - PAYMENT_PROCESSOR_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_FALLBACK=http://payment-processor-fallback:8080
      - POSTGRES_URL=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=payment_service
      - POSTGRES_MAX=3
      - POSTGRES_MIN=0
      - LOGGING_LEVEL_ROOT=OFF
      - LOGGING_LEVEL_COM_DOLPHS=OFF
      - PROCESSOR_RETRY_MAX=1800
      - CHUNK_SIZE=5
      - SPRING_SERVER_NETTY_EVENT_LOOP_THREADS=4
      - SPRING_SERVER_COMPRESSION_ENABLED=true
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: '0.45'
          memory: "80MB"
    depends_on:
      postgres:
        condition: service_healthy

  payment-service-2:
    image: tiagodolphine/rinha-2025-payment-service:0.0.2
    environment:
      - PAYMENT_PROCESSOR_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_FALLBACK=http://payment-processor-fallback:8080
      - SERVER_PORT=8080
      - POSTGRES_URL=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=payment_service
      - POSTGRES_MAX=3
      - POSTGRES_MIN=0
      - LOGGING_LEVEL_ROOT=OFF
      - LOGGING_LEVEL_COM_DOLPHS=OFF
      - PROCESSOR_RETRY_MAX=1800
      - CHUNK_SIZE=5
      - SPRING_SERVER_NETTY_EVENT_LOOP_THREADS=4
      - SPRING_SERVER_COMPRESSION_ENABLED=true
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: '0.45'
          memory: "80MB"
    depends_on:
      postgres:
        condition: service_healthy

  caddy:
    image: caddy:alpine
    container_name: caddy-lb
    volumes:
      - ./caddy.conf:/etc/caddy/Caddyfile:ro
    ports:
      - "9999:9999"
    depends_on:
      - payment-service-1
      - payment-service-2
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: "50MB"
    networks:
      - backend

#  nginx:
#    image: nginx:alpine
#    container_name: nginx-lb
#    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf:ro
#    ports:
#      - "9999:9999"
#    depends_on:
#      - payment-service-1
#      - payment-service-2
#    deploy:
#      resources:
#        limits:
#          cpus: '0.2'
#          memory: "40MB"
#    networks:
#      - backend

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: payment_service
      POSTGRES_MAX_CONNECTIONS: 50
    ports:
      - "5432:5432"
    command:
      - postgres
      - -c
      - shared_buffers=8MB
      - -c
      - work_mem=512kB
      - -c
      - maintenance_work_mem=4MB
      - -c
      - effective_cache_size=64MB
      - -c
      - fsync=off
      - -c
      - synchronous_commit=off
      - -c
      - full_page_writes=off
      - -c
      - wal_level=minimal
      - -c
      - max_connections=50
      - -c
      - max_wal_senders=0
    volumes:
      - type: tmpfs
        target: /var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: 140MB
    networks:
      - backend
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 2s
      timeout: 20s
      retries: 20

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true